### PR TITLE
Testing to Develop 1/14/21

### PR DESCRIPTION
**Pull request by michaelmeyer26**

### CODE REVIEW

**Comment by michaelmeyer26** [comment]
Ryan and Donelle, idk if y'all are still working and which of these issues might be solved, but these are the problems I've run into:

~~1. On the create route page, there is a small box underneath the map that doesn't actually contain anything.~~ **Intentional, this is where the directions will show after a route is checked out**
~~2. Also on the create route page, the styling for the checkbox didn't seem to make it in.~~
~~3. Unable to submit a comment for a route I had just created, it gives a 500 internal server error and takes us to our rickroll page.~~
~~4. Unable to submit a comment for an individual POI. Same error.~~
~~5. Single Event View still missing background behind right column.~~
~~6. Single Event view still has geolocation when it was taken out of every other map.~~
~~7. Single Event View has a "Back to All Events" button above the main container, but neither single POIs nor single Routes do.~~
~~8. Styling of submitted routes, POIs, and Events not present.~~ **Added by Donelle**
~~9. User profile pic still not updating.~~
~~10. When editing a route and you clear it, map defaults to zoomed-out view of US instead of geocoding user's location.~~
~~11. When adding a route, the clear route and see route buttons are above and to the right of the map and the round trip checkbox is above and to the left. When editing a route, they are in reversed position.~~
~~12. "Open in google maps" button on single route view still has no functionality.~~ **Commented out until functionality can be added**
~~13. Edit Point Page "Add a picture" button is the same color as the background.~~
~~14. Same issue as 13 but for events.~~
~~15. Edit Point page will pan back to the original location of your marker even if you've moved it, which is really annoying. It will even pan back if you're still adjusting the view, so that feature might have to be taken out as I won't have time to fix it tonight on top of other stuff. It's also something I'd be happy to tackle over the weekend if we feel strongly about keeping in.~~ **Removed from edit point page, intentionally left in view point**
~~16. Same issue as 15 but for the Edit event, individual event, and individual POI. Functionality is probably fine on the view pages but def needs to change for the edit pages.~~ **Removed from edit event page, intentionally left in view event**
17. Still no form model binding on update event radio boxes. Since there's no validation, if you don't select a category every time you edit and try and submit a change without selecting one you will hit an error page.
18. We legally need to attribute our icons as part of the license we used to obtain them. I would put something like "Icons from iconshock.com" kind of small in the footer and make sure it links to their website. 

That's everything I can find. **Biggest issue is probably commenting not working.** I will be working to fix some of the smaller I know how to fix tonight and commenting below so you know what I'm working on.

**Comment by michaelmeyer26** [comment]
I'll start working on #6 and pull when it's done

**Comment by michaelmeyer26** [comment]
Working on no. 7

**Comment by michaelmeyer26** [comment]
Working on 12 and 13

**Review by RMK1775 — COMMENTED** [review]
- About Us: Project description to match spreadsheet
- ~~Footer: Space between A and CODEUP~~ Fixed via PR #135
- Footer: Logo links to home page
#### Users
- ~~Register Page: Placeholder still goes below the field versus above~~ Donelle: UX removed
- ~~Edit Password: mismatch between new and confirm = error page~~ Donelle fixed
- ~~Profile page:~~ Donelle fixed 
>- ~~remove underlining from content~~
>>- ~~Maybe a highlight and bold text~~
>- ~~Routes, POIs, Events:~~ Fixed via PR #135
>>- ~~Deleting an item always selects the first one not the associated one~~  
#### Routes
- Add a Route: _stair step_ look of buttons above map
>- Resize to one row?
- Edit A Route: input validation doesn't happen
- ~~View a Route: remove "Open in Google Maps" button~~ Commented out in Michael's push
#### POIs
- ~~Edit POI: Add A Picture button is camo'd~~
#### Events
- Edit Event: 
>- Category doesn't preselect from original choice
>- ~~Add A Picture button is camo'd~~
#### Maps
##### Not Logged In and Logged In
- "Enter A Location" field: Los Angeles + return key:
>- On All (content) page = error page
>>- http://localhost:8081/all/search?locationinput=los+angeles
>>- Changing URL versus using js file
>- All Routes, All POIs, All Events = centered on CONUS(not logged in), on zipcode(logged in)
>>- http://localhost:8081/routes?locationinput=los+angeles
##### Not Logged In
- "Enter A Location" field: city and "View Location" button:
>- All Routes, All POIs, All Events: centers but no zoom

**Review by Jason-Carrillo — COMMENTED** [review]
Only issue I was able to find was default image error when editing a profile image using the placeholder default image.

**Review by Jason-Carrillo — APPROVED** [review]

**Comment by RMK1775** [comment]
Everything looks as intended

**Review by RMK1775 — APPROVED** [review]
Everything looks good for today's iteration

**Pull request merged**
